### ISSUE TITLE
Remove ^ hats from dependencies

### ISSUE THREAD

**Issue by bnolan** [GoogleChrome/big-rig#40]
The hats in the dependencies of the test-runner are installing an incompatible version of `selenium-webdriver` that has this error:

```/Users/bnolan/Work/runner/big-rig/test-runner/driver.js:88
  return (new webdriver.WebDriver.Logs(browser))
          ^

TypeError: webdriver.WebDriver.Logs is not a function
    at Object.getTrace (/Users/bnolan/Work/runner/big-rig/test-runner/driver.js:88:11)
    at Object.<anonymous> (/Users/bnolan/Work/runner/big-rig/test-runner/runner.js:117:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3```

 If you remove the hats and `npm install` it works again.

**Comment by bnolan** [comment]
You might call is a _caret_ instead of a _hat_. 😆
